// AWS Amplify v6 configuration for Cognito authentication  
// Auto-generated by scripts/generate_aws_exports.py - DO NOT EDIT MANUALLY
const awsconfig = {
  Auth: {
    Cognito: {
      userPoolId: 'ap-southeast-2_u6zH1Pbty',
      userPoolClientId: '2chnp95qkugngcet88uiokikpm',
      identityPoolId: 'ap-southeast-2:f1c9fbd0-085a-4639-93eb-309b62d03e08',
      loginWith: {
        email: true,
        oauth: {
          domain: 'sflt-auth.auth.ap-southeast-2.amazoncognito.com',
          scopes: ['email', 'openid', 'profile'],
          redirectSignIn: ["http://localhost:5173/", "https://d3nteozhns257o.cloudfront.net/"],
          redirectSignOut: ["http://localhost:5173/", "https://d3nteozhns257o.cloudfront.net/"],
          responseType: 'code',
          providers: ['Google'],
        },
      },
    },
  },
}

export default awsconfig
